name: taskit
description: "Taskit - task it easy."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.5
  path: ^1.9.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  credential_manager: ^2.0.3

  syncfusion_flutter_calendar: ^24.2.4
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint:
  build_runner: ^2.4.11
  freezed: ^2.4.6
  json_annotation: ^4.8.1
  json_serializable: ^6.8.0

  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10


  objectbox_generator: ^4.1.0


  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/taskit_app_icon.png"



