// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/event_model/event_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6837756959810003695),
      name: 'EventModel',
      lastPropertyId: const obx_int.IdUid(9, 2925991097565853482),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4727968746896605052),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 701065391642746900),
            name: 'eventName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7577110217412048422),
            name: 'from',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2298178397867413283),
            name: 'to',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9112330229300121),
            name: 'isAllDay',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8090136402069223623),
            name: 'isCompleted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4320191208980539107),
            name: 'notes',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2925991097565853482),
            name: 'badgeId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 6837756959810003695),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [8690936442615295391],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    EventModel: obx_int.EntityDefinition<EventModel>(
        model: _entities[0],
        toOneRelations: (EventModel object) => [],
        toManyRelations: (EventModel object) => {},
        getId: (EventModel object) => object.id,
        setId: (EventModel object, int id) {
          object.id = id;
        },
        objectToFB: (EventModel object, fb.Builder fbb) {
          final eventNameOffset = fbb.writeString(object.eventName);
          final notesOffset = fbb.writeString(object.notes);
          final badgeIdOffset = fbb.writeString(object.badgeId);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, eventNameOffset);
          fbb.addInt64(2, object.from.millisecondsSinceEpoch);
          fbb.addInt64(3, object.to.millisecondsSinceEpoch);
          fbb.addBool(4, object.isAllDay);
          fbb.addBool(5, object.isCompleted);
          fbb.addOffset(6, notesOffset);
          fbb.addOffset(8, badgeIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final eventNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final fromParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final toParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final isAllDayParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final isCompletedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final badgeIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final notesParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final object = EventModel(
              id: idParam,
              eventName: eventNameParam,
              from: fromParam,
              to: toParam,
              isAllDay: isAllDayParam,
              isCompleted: isCompletedParam,
              badgeId: badgeIdParam,
              notes: notesParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EventModel] entity fields to define ObjectBox queries.
class EventModel_ {
  /// See [EventModel.id].
  static final id =
      obx.QueryIntegerProperty<EventModel>(_entities[0].properties[0]);

  /// See [EventModel.eventName].
  static final eventName =
      obx.QueryStringProperty<EventModel>(_entities[0].properties[1]);

  /// See [EventModel.from].
  static final from =
      obx.QueryDateProperty<EventModel>(_entities[0].properties[2]);

  /// See [EventModel.to].
  static final to =
      obx.QueryDateProperty<EventModel>(_entities[0].properties[3]);

  /// See [EventModel.isAllDay].
  static final isAllDay =
      obx.QueryBooleanProperty<EventModel>(_entities[0].properties[4]);

  /// See [EventModel.isCompleted].
  static final isCompleted =
      obx.QueryBooleanProperty<EventModel>(_entities[0].properties[5]);

  /// See [EventModel.notes].
  static final notes =
      obx.QueryStringProperty<EventModel>(_entities[0].properties[6]);

  /// See [EventModel.badgeId].
  static final badgeId =
      obx.QueryStringProperty<EventModel>(_entities[0].properties[7]);
}
